language: node_js
node_js:
  - '12.13'
script: npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: altay.aydemir@gmail.com
  api_key:
    secure: FzOAE2F/eiyJypjEek1oNnkWPYRWHro1rxBwBpJRUUwUzl6EU7258SZHOcVlPslOl8YFismhqeZl8ZMWBmpKidP8gsVHXNcKvwcOslmu4qh9fkUmgJ8r1Xrb4EfiMKbugJeSgSOO8D6x1gZEHQHPqcy1+VFCdDJ3OErdSbTcbMc52eMJuJhss6Oi5KKTY4LEE/3OXhBqJh5YCgBaennqaiX4JMgGsU/QgKYhshcqp/5AkGgbkdsxJl6+ShlsuTwtBfXexIgAJgU0Zoo0QPEBjZhX2Se5/gd3Xgic+3GptmqPE0h9zFKk4RwgTGrV5j6Fs/R9p3Rbex6YZMC8QiIYei4ONUqvbRlIZL5oxRSDNcpfFVAC5VUYTovjxbVdyQGM7qDyDDUXMEcMWTj4HLwpv04IkjOTLevVZPfbUR8Qon4fwRl6fXgrDy0zkOmrtM4AJ7PyLrsAvE9dFp2wVcrh3KR7rnpNdhkTis6y3S8qV4ytZt3V4H8/a0q5eoPxGTVeAoVDC8Wcn2hYuzSDRE2KNFq8+Q3p6hfp1DR73NCcQ4hjvzydpgIEfmGub06cgKSDPuiwKXX3b/QbKfHRB03FFWbyvFmQaNopsAjKd6qKIb+4JN8QiuOW4WPNd7fyaxRui43mWceOWbbDMCDVFw7AhubcDgtC8upOaL9gJdB2pRM=
  on:
    tags: true
    repo: putdotio/putio.js
